encyclopedia/urls.py
from django.urls import path

from .views import index_view, search_view, entry_view, new_view, edit_view

app_name = "encyclopedia"
urlpatterns = [
    path("", index_view, name="index"),
    path("search", search_view, name="search"),
    path("new", new_view, name="new"),
    path("edit/<str:entry>", edit_view, name="edit"),
    path("<str:entry>", entry_view, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms/edit_form.py
from django.forms import Form, CharField, Textarea

class EditForm(Form):
    data = CharField(min_length=1, label="Entry content*", required=False, widget=Textarea())

encyclopedia/forms/new_form.py
from django.forms import Form, CharField, TextInput, Textarea
from django.core.validators import RegexValidator

from ..util import list_entries

validate_entry_title = RegexValidator( rf"^(?!.*\b({"|".join(list_entries())})\b).*$" )

class NewForm(Form):
    title = CharField(validators=[validate_entry_title], min_length=1, max_length=200, label="Entry title", widget=TextInput(attrs={"pattern":rf"^(?!.*\b({"|".join(list_entries())})\b).*$"}))
    data = CharField(min_length=1, label="Entry content*", required=False, widget=Textarea())

encyclopedia/forms/search_form.py
from django.forms import Form, CharField, TextInput

class SearchForm(Form):
    search = CharField(label="",widget=TextInput(attrs={"placeholder": "Search Encyclopedia", "class":"search"}))

encyclopedia/controllers/default.py
from numpy.random import randint

from ..forms import SearchForm
from ..util import list_entries


render_data = { 
    "SearchForm": SearchForm(),
    "random_entry": list_entries()[randint(1, len(list_entries()))]
}

encyclopedia/controllers/edit.py
from django.shortcuts import redirect
from urllib.parse import quote_plus
from numpy.random import randint
from django.urls import reverse

from ..util import save_entry, get_entry, list_entries
from ..forms import EditForm
from .default import render_data


def edit_post_controller(request, entry):
    form_response = EditForm(request.POST)
    render_data["entry"] = entry
    
    if form_response.is_valid():
        save_entry(entry, form_response.cleaned_data["data"])
        
        return redirect(reverse("encyclopedia:entry", args=(quote_plus(entry),)))
    else: 
        render_data["EditForm"] = form_response
        
    return render_data

def edit_get_controller(entry) -> dict:
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    
    render_data.update({ 
        "EditForm": EditForm({"data":get_entry(entry)}),
        "entry":entry
    })

    return render_data

encyclopedia/controllers/entry.py
from urllib.parse import unquote
from numpy.random import randint
from markdown2 import Markdown

from ..util import get_entry, list_entries
from .default import render_data


def entry_controller(entry) -> dict:
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    
    entry = unquote(entry)
    
    if (data := get_entry(entry)):
        data = Markdown().convert(data)
        default = None
    else:
        default = f"<h1>Error 404.</h1><br><h3>Entry '{entry}' not found</h3>"
    
    render_data.update({
        "data": data,
        "entry": entry,
        "default": default,
    })
    
    return render_data

encyclopedia/controllers/index.py
from ..util import list_entries
from .default import render_data

from numpy.random import randint


def index_controller():
    render_data["entries"] = list_entries()
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    
    return render_data

encyclopedia/controllers/new.py
from django.shortcuts import redirect
from urllib.parse import quote_plus
from numpy.random import randint
from django.urls import reverse

from ..util import save_entry, list_entries
from ..forms import NewForm
from .default import render_data


def new_post_controller(request):
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    
    form_response = NewForm(request.POST)
    
    if form_response.is_valid():
        save_entry(form_response.cleaned_data["title"], form_response.cleaned_data["data"])
        
        return redirect(reverse("encyclopedia:entry", args=(quote_plus(form_response.cleaned_data["title"]),)))
    else: 
        render_data["NewForm"] = form_response
        
    return render_data

def new_get_controller(request) -> dict:
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    render_data["NewForm"] = NewForm()

    return render_data

encyclopedia/controllers/search.py
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import redirect
from urllib.parse import quote_plus
from numpy.random import randint
from django.urls import reverse

from ..util import get_entry, list_entries
from ..forms.search_form import SearchForm
from .default import render_data


def search_controller(request) -> dict|HttpResponseRedirect|HttpResponsePermanentRedirect:
    search_raw = SearchForm(request.POST)
    render_data["random_entry"] = list_entries()[randint(1, len(list_entries()))]
    
    if search_raw.is_valid():
        if get_entry(search := str(search_raw.cleaned_data["search"]).lower().capitalize()):
            return redirect(reverse("encyclopedia:entry", args=(quote_plus(search))))
        else:
            if not (coincidences := [entry for entry in list_entries() if search.lower() in entry.lower()]):
                render_data["default"] = f"No coincidence found for '{search_raw.cleaned_data["search"]}' "
            else:
                render_data["coincidences"] = coincidences
        render_data["search"] = search
        render_data["search_raw"] = search_raw.cleaned_data["search"]
    else:
        return redirect(reverse("encyclopedia:index"))
    
    return render_data

encyclopedia/views/edit.py
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import render

from ..controllers import edit_post_controller, edit_get_controller


def edit_view(request, entry):
    if request.POST:
        
        if isinstance((search_result := edit_post_controller(request, entry)), HttpResponseRedirect|HttpResponsePermanentRedirect):
            return search_result
        
        return render(request, "encyclopedia/edit.html", search_result)
    else:
        return render(request, "encyclopedia/edit.html", edit_get_controller(entry))

encyclopedia/views/entry.py
from django.shortcuts import render

from ..controllers import entry_controller


def entry_view(request, entry):
    return render(request, "encyclopedia/entry.html", entry_controller(entry))

encyclopedia/views/index.py
from django.shortcuts import render

from ..controllers import index_controller


def index_view(request):
    return render(request, "encyclopedia/index.html", index_controller())

encyclopedia/views/new.py
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import render

from ..controllers import new_post_controller, new_get_controller


def new_view(request):
    if request.POST:
        
        if isinstance((search_result := new_post_controller(request)), HttpResponseRedirect|HttpResponsePermanentRedirect):
            return search_result
        
        return render(request, "encyclopedia/new.html", new_post_controller(request))
    else:
        return render(request, "encyclopedia/new.html", new_get_controller(request))

encyclopedia/views/search.py
from django.http import (HttpResponsePermanentRedirect, HttpResponseRedirect)
from django.shortcuts import render

from ..controllers import search_controller


def search_view(request):
    if request.method == "POST":
        
        if isinstance((search_result := search_controller(request)), HttpResponseRedirect|HttpResponsePermanentRedirect):
            return search_result
        
        return render(request, "encyclopedia/search.html", search_result)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Edit {{entry}}
{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
    <h1>Edit wiki entry</h1>

    <form action="{% url 'encyclopedia:edit' entry %}" method="post" style="margin-right:10%">
        {% csrf_token %}
        {{ EditForm|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

    <script>
        const easyMDE = new EasyMDE();
    </script>

{% endblock %}


{% block scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
    <script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ entry }}
{% endblock %}

{% block body %}
    <a href="{% url 'encyclopedia:edit' entry %}" st>Edit entry</a>
    {% autoescape off %}
        {{ data|default_if_none:default }}
    {% endautoescape %}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:entry' entry %}"> {{ entry }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block scripts %}
        {% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ SearchForm }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:entry' random_entry %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - New entry
{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
    <h1>New wiki entry</h1>

    <form action="{% url 'encyclopedia:new' %}" method="post" style="margin-right:10%">
        {% csrf_token %}
        {{ NewForm|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

    <script>
        const easyMDE = new EasyMDE();

        $(function(){
            $("input[id=id_title]")[0].oninvalid = function () {
                if (this.validity.patternMismatch){
                    this.setCustomValidity("This entry already exists.");
                }
            };
        });

        $(function(){
            $("input[id=id_title]")[0].oninput= function () {
                this.setCustomValidity("");
            };
        });
    </script>

{% endblock %}


{% block scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
    <script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Search '{{search}}'
{% endblock %}

{% block body %}
    {% if coincidences %}

    <h1>All results for {{search_raw}}</h1>

    <ul>
        {% for coincidence in coincidences %}
            <li> <a href="{% url 'encyclopedia:entry' coincidence %}"> {{ coincidence }} </a> </li>
        {% endfor %}
    </ul>

    {% else %}

    <h1> {{default}} </h1>

    {% endif %}

{% endblock %}